export interface AdditionalProduct {
    ProductTitle: string,
    ProductQuantity: number,
    ProductPrice: number,
    ProductTypeId: string,
    OnlyOneType: boolean,
    Checked: string,
    ProductInformation: string,
    CommonType: string,
    BtnToOff: null,
    CommonName: string,
    CommonDescription: string,
    ProductImage: string,
    ImageStile: string,
    TitleStyleColor: string,
    InformationStyleColor: string,
    RadioElementBlockStyle: string,
    AdditionalInputParameters: string,
    available: OnOff,
    btn: any,
    displayInTheBagList: boolean
}

type OnOff = "on" | "off";

export interface AdditionalProducts {
    insuranceProductData: AdditionalProduct,
    expressProductData: AdditionalProduct,
    standardProductData: AdditionalProduct,
    firstPresentProductData: AdditionalProduct,
    secondPresentProductData: AdditionalProduct,
    pobranieProductData: AdditionalProduct
    onlineProductData: AdditionalProduct
    warrantyData: AdditionalProduct
}

export const additionalProducts: AdditionalProducts = {
    insuranceProductData: {
        "ProductTitle": "Ubezpieczenie Przesyłki",
        "ProductQuantity": 1,
        "ProductPrice": 19,
        "ProductTypeId": "ubezpieczenie",
        "OnlyOneType": true,
        "Checked": "checked",
        "ProductInformation": `Ubezpiecz swoją przesyłkę za jedynie 19 zł (opcjonalnie)`,
        "CommonType": "ubezpieczenie",
        "BtnToOff": null,
        "CommonName": "Ubezpieczenie",
        "CommonDescription": "Ubezpieczenie dotyczy uszkodzenia przesyłki - jeśli product zostanie uszkodzony podczas" +
            " dostawy, wyślemy Tobie natychmiast nowy product.",
        "ProductImage": "https://drive.google.com/uc?export=view&id=1Bts7iDrTFAkfyw1ZU-ioj9-QCdtN5F4N",
        "ImageStile": "",
        "TitleStyleColor": "color:#478b05;",
        "InformationStyleColor": "color:#478b05;",
        "RadioElementBlockStyle": "",
        "AdditionalInputParameters": "",
        "available": "on",
        "btn": undefined,
        "displayInTheBagList": true
    },
    expressProductData: {
        "ProductTitle": "Express delivery",
        "ProductQuantity": 1,
        "ProductPrice": 20,
        "ProductTypeId": "express",
        "OnlyOneType": true,
        "Checked": "",
        "ProductInformation": `Przesyłka expresowa (1-2 dni): 20 zł`,
        "CommonType": "delivery",
        "BtnToOff": null,
        "CommonName": "Opcje Dostawy",
        "CommonDescription": "",
        "ProductImage": "https://drive.google.com/uc?export=view&id=1wJMgzdmazH7XhM_-S54HVm2TsztNYRt4",
        "ImageStile": "",
        "TitleStyleColor": "",
        "InformationStyleColor": "",
        "RadioElementBlockStyle": "",
        "AdditionalInputParameters": "",
        "available": "on",
        "btn": undefined,
        "displayInTheBagList": true
    },
    standardProductData: {
        "ProductTitle": "Standard delivery",
        "ProductQuantity": 1,
        "ProductPrice": 0,
        "ProductTypeId": "standard",
        "OnlyOneType": true,
        "Checked": "checked",
        "ProductInformation": `Przesyłka standardowa(3-5 dni): 0 zł`,
        "CommonType": "delivery",
        "BtnToOff": null,
        "CommonName": "Opcje Dostawy",
        "CommonDescription": "",
        "ProductImage": "",
        "ImageStile": "",
        "TitleStyleColor": "",
        "InformationStyleColor": "",
        "RadioElementBlockStyle": "",
        "AdditionalInputParameters": "",
        "available": "on",
        "btn": undefined,
        "displayInTheBagList": false
    },
    firstPresentProductData: {
        "ProductTitle": "NIESPODZIANKA OD MIKOLAJA",
        "ProductQuantity": 1,
        "ProductPrice": 22.30,
        "ProductTypeId": "niespodzianka",
        "OnlyOneType": true,
        "Checked": "",
        "ProductInformation": "Niespodzianka od Mikołaja tylko 22,30 zł (opcjonalnie)",
        "CommonType": "niespodzianka",
        "BtnToOff": null,
        "CommonName": "first-niespodzinka",
        "CommonDescription": "Nie mogą Państwo przegąbić tej wyjątkowej niespodzinki od Świętego Mikołaja. Prezent o wartości ponad 90,00 zł jest dostępny w niesamowito nisakiej cenie 22,30 zł.",
        "ProductImage": "https://drive.google.com/uc?export=view&id=1o8ZFta1--HccDvEmMWeaBqHQxL1dfBGB",
        "ImageStile": "",
        "TitleStyleColor": "color: #F5880C;",
        "InformationStyleColor": "color: #F5880C;",
        "RadioElementBlockStyle": "",
        "AdditionalInputParameters": "",
        "available": "on",
        "btn": undefined,
        "displayInTheBagList": true
    },
    secondPresentProductData: {
        "ProductTitle": "Werniks super 3D efekt",
        "ProductQuantity": 1,
        "ProductPrice": 49,
        "ProductTypeId": "second-niespodzianka",
        "OnlyOneType": true,
        "Checked": "",
        "ProductInformation": "Werniks dodaje mega 3D efekt do twojego obrazu. Powłoka tworzy swoistą dodatkową barirę ochronną dla naszego obrazu (49 zł)",
        "CommonType": "second-niespodzianka",
        "BtnToOff": null,
        "CommonName": "Second Niespodzianka",
        "CommonDescription": "",
        "ProductImage": "https://drive.google.com/uc?export=view&id=1lv1Rr_SDLhEmPTV5lvN508znAyUoJhIx",
        "ImageStile": "border-radius: 10%;",
        "TitleStyleColor": "color: #F5880C;",
        "InformationStyleColor": "color: #F5880C;",
        "RadioElementBlockStyle": "",
        "AdditionalInputParameters": "",
        "available": "off",
        "btn": undefined,
        "displayInTheBagList": true
    },
    pobranieProductData: {
        "ProductTitle": "Przesyłka za pobraniem",
        "ProductQuantity": 1,
        "ProductPrice": 29,
        "ProductTypeId": "pobranie",
        "OnlyOneType": true,
        "Checked": "checked",
        "ProductInformation": "Przesyłka za pobraniem: 29 zł",
        "CommonType": "płatność",
        "BtnToOff": null,
        "CommonName": "Płatność",
        "CommonDescription": "",
        "ProductImage": "https://drive.google.com/uc?export=view&id=10YPdzH1Sy2QtJ7rnN0OLY0_4Br9EiVAC",
        "ImageStile": "",
        "TitleStyleColor": "",
        "InformationStyleColor": "",
        "RadioElementBlockStyle": "",
        "AdditionalInputParameters": "",
        "available": "on",
        "btn": undefined,
        "displayInTheBagList": true
    },
    onlineProductData: {
        "ProductTitle": "Online",
        "ProductQuantity": 1,
        "ProductPrice": 0,
        "ProductTypeId": "online",
        "OnlyOneType": true,
        "Checked": "",
        "ProductInformation": "Płatność online(Stripe): 0 zł",
        "CommonType": "płatność",
        "BtnToOff": null,
        "CommonName": "Płatność",
        "CommonDescription": "",
        "ProductImage": "",
        "ImageStile": "",
        "TitleStyleColor": "",
        "InformationStyleColor": "",
        "RadioElementBlockStyle": "",
        "AdditionalInputParameters": "",
        "available": "on",
        "btn": undefined,
        "displayInTheBagList": false
    },
    warrantyData: {
        "ProductTitle": "+2 lata gwarancji",
        "ProductQuantity": 1,
        "ProductPrice": 15,
        "ProductTypeId": "gwarancja",
        "OnlyOneType": true,
        "Checked": "",
        "ProductInformation": "Wybierz +2 lata gwarancji (15 zł)",
        "CommonType": "gwarancja",
        "BtnToOff": null,
        "CommonName": "Gwarancja",
        "CommonDescription": "",
        "ProductImage": "https://drive.google.com/uc?export=view&id=13dw4g8Ibz8K3XrNo2c1-s_E-Q-KR8rTS",
        "ImageStile": "",
        "TitleStyleColor": "color:#478b05;",
        "InformationStyleColor": "color:#478b05;",
        "RadioElementBlockStyle": "",
        "AdditionalInputParameters": "",
        "available": "on",
        "btn": undefined,
        "displayInTheBagList": true
    }
}